trigger:
  branches:
    include:
    - main
    - feature/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  displayName: 'Use Node 14.x'
  inputs:
    versionSpec: 14.x
- task: Npm@1
  displayName: 'npm install'
  inputs:
    workingDir: src
    verbose: false
